"""empty message

Revision ID: 175edb69b15b
Revises: 0a1ccc575eba
Create Date: 2024-03-28 20:35:58.902938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175edb69b15b'
down_revision = '0a1ccc575eba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bugreportcomments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bug_report_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.username'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bug_report_id'], ['bugreports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bugreports', sa.Column('closed_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bugreports', 'closed_by')
    op.drop_table('bugreportcomments')
    # ### end Alembic commands ###
