"""empty message

Revision ID: 2ecb128fe207
Revises: 23fa14e3ff70
Create Date: 2024-03-28 20:53:56.049990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecb128fe207'
down_revision = '23fa14e3ff70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
