"""empty message

Revision ID: 37682c7e32f6
Revises: cdb7c14e1d59
Create Date: 2024-03-19 21:39:17.721080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37682c7e32f6'
down_revision = 'cdb7c14e1d59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('viped_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'viped_at')
    # ### end Alembic commands ###
