"""empty message

Revision ID: 3a98917e5eea
Revises: 6b7ae8fdce87
Create Date: 2024-02-29 15:29:54.837791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a98917e5eea"
down_revision = "6b7ae8fdce87"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
