"""empty message

Revision ID: 4c00bd300399
Revises: c24510023176
Create Date: 2024-03-26 15:52:56.497737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c00bd300399'
down_revision = 'c24510023176'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
