"""empty message

Revision ID: 6b7ae8fdce87
Revises: 9f1a953c6a42
Create Date: 2024-02-29 15:27:36.204038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7ae8fdce87'
down_revision = '9f1a953c6a42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
