"""empty message

Revision ID: 9c732fbccf8a
Revises: 37682c7e32f6
Create Date: 2024-03-25 19:26:53.903938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c732fbccf8a'
down_revision = '37682c7e32f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
