"""empty message

Revision ID: a1182b07c592
Revises: 3a98917e5eea
Create Date: 2024-02-29 23:08:35.958099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a1182b07c592"
down_revision = "3a98917e5eea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    # ### end Alembic commands ###
