"""empty message

Revision ID: faed64b7a0a6
Revises: 2ecb128fe207
Create Date: 2024-03-30 01:34:14.867829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faed64b7a0a6'
down_revision = '2ecb128fe207'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
