"""test

Revision ID: fd55859579fb
Revises: bfbe6f797df0
Create Date: 2024-02-20 04:38:23.514234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd55859579fb'
down_revision = 'bfbe6f797df0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
