version: '3.8'

services:

  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
    depends_on:
      - backend

  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    command: 'sh -c "alembic upgrade head && python app/main.py --host 0.0.0.0 --port 8000"'
    depends_on:
      - alx-db


  alx-db:
    container_name: alx-db
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    depends_on:
      - alx-db

  redis-cache:
    image: redis:alpine
    hostname: redis-cache
    container_name: redis-cache
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data

  worker:
    container_name: worker
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile 
    entrypoint: ["celery"]
    command: ["-A", "app.configs.celery", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    depends_on:
      - alx-db
      - backend
      - redis-cache

  flower:
    container_name: flower
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile     
    entrypoint: ["celery"]
    command: ["-A", "app.configs.celery", "flower", "--port=5555"]
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - backend
      - redis-cache
      - worker

volumes:
  postgres_data:
  cache: